export { api, ApiError } from './client';
export { authApi } from './auth';
export { messagesApi } from './messages';
export { pupilsApi } from './pupils';
export { notificationsApi } from './notifications';
export { rosterApi } from './roster';
export { teacherApi } from './teacher';
export { schoolPath } from './tenant';
export type { ClassItem, RosterPupil } from './roster';
export type { Subject, TermItem } from './teacher';
export type { MessageItem, ReplyItem, MessageDetail } from './messages';
export type { PupilSummary } from './pupils';
export type { AppNotification } from './notifications';
export type { LoginResponse } from './auth';
